services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    depends_on:
      db:
        condition: service_healthy
    networks: [devnet]

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: geheim
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [devnet]

  pgadmin:
    image: dpage/pgadmin4:9.7
    ports: ["5050:80"]
    depends_on:
      db:
        condition: service_healthy
    networks: [devnet]

networks:
  devnet: {}
